apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup-bucket.yaml
  - cnpg-backup.yaml
  - cnpg-cluster.yaml
  - externalsecrets.yaml
  - kiosk.yaml
  - pvc-library.yaml
