---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  hostnames:
    - ha.civilsnut.se
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: gateway-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: home-assistant
          port: 8123
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
