apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  timeout: 30m
  dependsOn:
    - name: rook-ceph-operator
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      mon:
        count: 3
        allowMultiplePerNode: false
      mgr:
        count: 2
        allowMultiplePerNode: false
      dashboard:
        enabled: true
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: wrk-01
            devices:
              - name: nvme0n1
          - name: wrk-02
            devices:
              - name: nvme0n1
          - name: wrk-03
            devices:
              - name: nvme0n1
          - name: wrk-04
            devices:
              - name: nvme0n1
      placement:
        all:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: has-disk
                      operator: In
                      values:
                        - "yes"
      resources:
        mon:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
        osd:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 2Gi
        mgr:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems: []
    cephObjectStores: []
    monitoring:
      enabled: true
      createPrometheusRules: false
