---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-gateway-controller
  namespace: gateway-system
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shared-gateway-manager
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
rules:
  # Gateway API resources
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - gateways/status
      - httproutes
      - httproutes/status
      - referencegrants
      - gatewayclasses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Core resources for gateway functionality
  - apiGroups: [""]
    resources:
      - services
      - services/status
      - endpoints
      - secrets
    verbs: ["get", "list", "watch"]
  
  # Namespace access for allowed namespaces
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]
  
  # Events for troubleshooting
  - apiGroups: [""]
    resources:
      - events
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shared-gateway-manager
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shared-gateway-manager
subjects:
  - kind: ServiceAccount
    name: shared-gateway-controller
    namespace: gateway-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-gateway-namespace-manager
  namespace: gateway-system
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
rules:
  # Full control over gateway-system namespace resources
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
      - services
      - serviceaccounts
    verbs: ["*"]
  
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
      - referencegrants
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-gateway-namespace-manager
  namespace: gateway-system
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-gateway-namespace-manager
subjects:
  - kind: ServiceAccount
    name: shared-gateway-controller
    namespace: gateway-system