---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-gateway
  namespace: argocd
  labels:
    app.kubernetes.io/name: shared-gateway
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/mrjson79/civilsnut-labb.git
    targetRevision: HEAD
    path: argocd/apps/shared-gateway
    directory:
      include: "{gateway.yaml,namespace.yaml,rbac.yaml,referencegrant.yaml}"
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
