apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-api-controller
  namespace: monitoring
  labels:
    app: gateway-api-controller
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-api
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
    - kube-system
    - gateway-system
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
  - port: webhook-metrics
    interval: 30s
    path: /metrics
    honorLabels: true
