apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: self-managed
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.1.3
      helm:
        valueFiles:
          - $values/argocd/apps/argocd/values.yaml
        parameters:
          - name: "server.ingress.enabled"
            value: "false"
          - name: "server.ingressGrpc.enabled"
            value: "false"
    - repoURL: https://github.com/mrjson79/civilsnut-labb
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mrjson79/civilsnut-labb
      targetRevision: HEAD
      path: argocd/apps/argocd
      directory:
        include: "{grpcroute.yaml,httproute.yaml,namespace.yaml,referencegrant.yaml,manifests/*.yaml}"
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3

  ignoreDifferences:
    - group: v1
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: v1
      kind: Secret
      jsonPointers:
        - /data
      name: argocd-secret
    - group: v1
      kind: ConfigMap
      jsonPointers:
        - /data/app.kubernetes.io/instance
      name: argocd-cm
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/sources/2/directory/jsonnet
        - /spec/syncPolicy/automated/prune
        - /spec/syncPolicy/automated/selfHeal
        - /spec/syncPolicy/automated/allowEmpty
        - /spec/syncPolicy/retry
