apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - externalsecrets.yaml
  - postgres.yaml
  - cnpg-cluster.yaml
  - backup-bucket.yaml
  - cnpg-backup.yaml
  - release.yaml
  - httproute.yaml
