apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd"
  prune: true
  wait: true
  postBuild:
    substitute: {}
  patches:
    # Ensure proper ordering of infrastructure components
    - target:
        kind: Kustomization
        name: cert-manager-release
      patch: |
        - op: add
          path: /spec/dependsOn
          value: []
    - target:
        kind: Kustomization
        name: ingress-nginx-release
      patch: |
        - op: add
          path: /spec/dependsOn
          value:
            - name: cert-manager-config
    - target:
        kind: Kustomization
        name: shared-gateway
      patch: |
        - op: add
          path: /spec/dependsOn
          value:
            - name: ingress-nginx-config
    - target:
        kind: Kustomization
        name: longhorn-release
      patch: |
        - op: add
          path: /spec/dependsOn
          value:
            - name: cert-manager-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: shared-gateway
      namespace: gateway-system
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-ui
      namespace: longhorn-system
