apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/external-secrets"
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-webhook
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-cert-controller
      namespace: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/onepassword-connect"
  prune: true
  wait: true

  targetNamespace: external-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: onepassword-connect
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: onepassword-connect-operator
      namespace: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/external-secrets/manifests"
  prune: true
  wait: true
  # No dependencies - external-secrets-config can deploy independently
  # dependsOn:
  #  - name: external-secrets-release
  # - name: onepassword-connect-release
  targetNamespace: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 20m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/kube-prometheus"
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-config
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/kube-prometheus/service-monitors"
  prune: true
  wait: true
  dependsOn:
    - name: kube-prometheus-release
  targetNamespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/cert-manager"
  prune: true
  wait: true

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/cert-manager/manifests"
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager-release
  targetNamespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/ingress-nginx"
  prune: true
  wait: true

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-config
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/ingress-nginx/manifests"
  prune: true
  wait: true
  dependsOn:
    - name: ingress-nginx-release
  targetNamespace: ingress-nginx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-gateway
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/shared-gateway"
  prune: true
  wait: true

  targetNamespace: gateway-system
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: shared-gateway
      namespace: gateway-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-release
  namespace: flux-system
spec:
  interval: 5m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/longhorn"
  prune: true
  wait: true

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-manager
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-ui
      namespace: longhorn-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mqtt
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/mqtt"
  prune: true
  wait: true
  targetNamespace: mosquitto
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/zigbee2mqtt"
  prune: true
  wait: true
  targetNamespace: zigbee2mqtt
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: zigbee2mqtt
      namespace: zigbee2mqtt
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 5m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/home-assistant"
  prune: true
  wait: true
  targetNamespace: home-assistant
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: home-assistant
      namespace: home-assistant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./fluxcd/cilium"
  prune: true
  wait: true
  targetNamespace: kube-system
