apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: ingress-controller
    app.kubernetes.io/part-of: infrastructure
