---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: podinfo-cert-access
  namespace: ingress-nginx
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: podinfo
  to:
  - group: ""
    kind: Secret
    name: civilsnut-se-wildcard-tls