apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-staging-cluster-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: vcluster-staging-cluster-secret
    app.kubernetes.io/component: cluster-secret
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/mrjson79/civilsnut-labb.git
    targetRevision: HEAD
    path: argocd/apps/vcluster-staging/manifests
    directory:
      include: "argocd-cluster-secret.yaml"
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
