apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cloudflare-api-token
    app.kubernetes.io/component: externalsecret
    app.kubernetes.io/managed-by: argocd
    app: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: cert-manager
  refreshInterval: 1h
  data:
    - secretKey: api-token
      remoteRef:
        key: "Cloudflare API Token"
        property: api-token
