---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
  labels:
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hostnames:
    - kubevirt-manager.civilsnut.se
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
  rules:
    - backendRefs:
        - name: kubevirt-manager
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
