---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  monitorNamespace: ""
  monitorAccount: ""
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - LiveMigration
        - Snapshot
        - HotplugVolumes
        - VirtualMachineExport
        - VMExport
        - ExpandDisks
        - CPUManager
        - GPU
        - HostDevices
        - HostDisk
        - Macvtap
        - Passt
        - clientPassthrough
        - CPUNodeDiscovery

      useEmulation: false
    network:
      defaultNetworkInterface: "masquerade"
      permitSlirpInterface: false
      permitBridgeInterfaceOnPodNetwork: false
    virtualMachineInstancesPerNode: 10
    migrations:
      parallelMigrationsPerCluster: 5
      parallelOutboundMigrationsPerNode: 2
      bandwidthPerMigration: "64Mi"
      completionTimeoutPerGiB: 800
      progressTimeout: 150
      allowAutoConverge: false
      allowPostCopy: false
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  infra:
    replicas: 2
    nodePlacement:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
  workloads:
    nodePlacement:
      nodeSelector:
        kubernetes.io/arch: arm64
