---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-manager
  labels:
    app.kubernetes.io/name: kubevirt-manager
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
