---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubevirt-cluster-critical
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
value: 1000000000
globalDefault: false
description: "Priority class for KubeVirt cluster-critical components like virt-handler"
