apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          global:
            nodeSelector:
              has-disk: "yes"
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultDataPath: /var/mnt/storage
          ingress:
            enabled: true
            ingressClassName: nginx
            host: longhorn.civilsnut.se
            path: /
            tls: true
            tlsSecret: civilsnut-se-wildcard-tls
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: 10000m
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
