apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/component: storage
        gateway.networking.k8s.io/allowed: "true"
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          global:
            nodeSelector:
              has-disk: "yes"
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultDataPath: /var/mnt/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/versions/*/schema/openAPIV3Schema/preserveUnknownFields
