apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsidp-authkey
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: tsidp-authkey
    creationPolicy: Owner
  data:
    - secretKey: authkey
      remoteRef:
        key: tsidp-authkey
        property: authkey
