apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: podinfo-production

namespace: podinfo-production

resources:
  - ../../base
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: production
      app.kubernetes.io/managed-by: kargo

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.9.0

configMapGenerator:
  - name: podinfo-config
    behavior: merge
    literals:
      - PODINFO_UI_COLOR=#2e8b57
      - PODINFO_UI_MESSAGE="🎯 Production Environment - Stable Release"
      - PODINFO_BACKEND_URL=""

replicas:
  - name: podinfo
    count: 3

patches:
  - path: patches/ingress-production.yaml
  - path: patches/deployment-production.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: podinfo.civilsnut.se
      - op: replace
        path: /spec/rules/0/host
        value: podinfo.civilsnut.se

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/environment: production
