apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hardware-flatcar-ctrl-1.yaml
  - template-flatcar.yaml
  - workflow-flatcar-ctrl-1.yaml
  - hardware-flatcar-wrk-1.yaml
  - workflow-flatcar-wrk-1.yaml
