apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  name: flatcar-ctrl-1
  namespace: tinkerbell
spec:
  templateRef: flatcar-amd64
  hardwareRef: flatcar-ctrl-1
  hardwareMap:
    device_1: "e8:6a:64:57:e3:fc"
