apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: podinfo-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: podinfo
  app.kubernetes.io/component: web-application

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.9.0

configMapGenerator:
  - name: podinfo-config
    literals:
      - PODINFO_UI_COLOR=#34577c
      - PODINFO_UI_MESSAGE="Hello from GitOps Pipeline"
      - PODINFO_BACKEND_URL=""

replicas:
  - name: podinfo
    count: 2
