apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-agent
  namespace: monitoring
  labels:
    app: cilium-agent
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  podMetricsEndpoints:
    - port: prometheus
      interval: 30s
      path: /metrics
      honorLabels: true
