apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.18.2
    helm:
      values: |
        installCRDs: true

        replicaCount: 2

        image:
          repository: ghcr.io/external-secrets/external-secrets
          pullPolicy: IfNotPresent
          tag: ""

        crds:
          createClusterExternalSecret: true
          createClusterSecretStore: true
          createPushSecret: true

        leaderElect: true

        controllerClass: ""

        scopedNamespace: ""
        scopedRBAC: false

        concurrent: 1

        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        nodeSelector:
          has-disk: "yes"

        tolerations: []

        affinity: {}

        podSecurityContext:
          fsGroup: 65534

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault

        serviceAccount:
          create: true
          annotations: {}
          name: ""
          automount: true

        rbac:
          create: true

        serviceMonitor:
          enabled: false
          namespace: ""
          interval: 30s
          scrapeTimeout: 25s
          labels: {}

        metrics:
          listen:
            port: 8080
          service:
            enabled: true
            port: 8080
            annotations: {}

        webhook:
          port: 9443
          create: true
          certCheckInterval: "5m"
          lookaheadInterval: "5m"
          replicaCount: 2
          failurePolicy: Ignore
          certDir: /tmp/k8s-webhook-server/serving-certs
          image:
            repository: ghcr.io/external-secrets/external-secrets
            pullPolicy: IfNotPresent
            tag: ""
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          nodeSelector:
            has-disk: "yes"
          tolerations: []
          affinity: {}
          podSecurityContext:
            fsGroup: 65534
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault

        certController:
          create: true
          requeueInterval: "5m"
          replicaCount: 1
          image:
            repository: ghcr.io/external-secrets/external-secrets
            pullPolicy: IfNotPresent
            tag: ""
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          nodeSelector:
            has-disk: "yes"
          tolerations: []
          affinity: {}
          podSecurityContext:
            fsGroup: 65534
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault

        processClusterStore: true
        processClusterExternalSecret: true

        createOperator: true

        extraArgs: {}

        extraEnv: []

        extraVolumes: []

        extraVolumeMounts: []

        deploymentAnnotations: {}

        podAnnotations: {}

        podLabels: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
