apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  source:
    chart: openbao
    repoURL: https://openbao.github.io/openbao-helm
    targetRevision: 0.13.2
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                storage "raft" {
                  path = "/openbao/data"
                }
                service_registration "kubernetes" {}
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          livenessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true"
            initialDelaySeconds: 60
          extraEnvironmentVars:
            OPENBAO_CLUSTER_INTERFACE: eth0
            OPENBAO_RAFT_NODE_ID: $(HOSTNAME)
          dataStorage:
            enabled: true
            storageClass: longhorn
            size: 10Gi
            accessMode: ReadWriteOnce
          nodeSelector:
            has-disk: "yes"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
            hosts:
              - host: openbao.civilsnut.se
                paths:
                  - path: /
                    pathType: Prefix
        ui:
          enabled: true
          serviceType: "ClusterIP"
        injector:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true