apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: zigbee2mqtt
      version: "2.7.1"
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: zigbee2mqtt
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      port: 8080

    statefulset:
      storage:
        enabled: true
        size: 1Gi
        storageClassName: ceph-block
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
      nodeSelector:
        has-disk: "yes"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]

    zigbee2mqtt:
      timezone: Europe/Stockholm
      homeassistant:
        enabled: true
        discovery_topic: "homeassistant"
        status_topic: "hass/status"
      permit_join: false
      mqtt:
        server: "mqtt://mosquitto.mosquitto.svc.cluster.local:1883"
        user: admin
        password: mystrongmqttpassword
      serial:
        port: "tcp://192.168.1.195:6638"
        adapter: zstack
      frontend:
        enabled: true
        port: 8080
        host: ""
      advanced:
        pan_id: 5576
        ext_pan_id: [0x1f, 0x3f, 0x10, 0x84, 0x43, 0x7d, 0x1e, 0x17]
        network_key:
          [
            0x55,
            0xc6,
            0xb4,
            0xd7,
            0xd5,
            0xc6,
            0x5b,
            0xcc,
            0xd2,
            0x03,
            0xd9,
            0x29,
            0x57,
            0x4c,
            0x4e,
            0xb7,
          ]
        channel: 20
        log_level: info
        cache_state: true
        last_seen: "ISO_8601"
        transmit_power: 5

    ingress:
      enabled: false

    # Environment variables to override MQTT credentials from secret
    extraEnvs:
      - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
        valueFrom:
          secretKeyRef:
            name: mqtt-credentials-secret
            key: username
      - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mqtt-credentials-secret
            key: password
