---
apiVersion: v1
kind: Service
metadata:
  name: icloud-photos
  namespace: icloud-photos
  labels:
    app: icloud-photos
spec:
  selector:
    app: icloud-photos
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
