apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-web-oidc
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: flux-web-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: flux-web-oidc
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: flux-web-oidc
        property: client_secret
