apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - flux-web-oidc-externalsecret.yaml
  - resourceset.yaml
  - httproute.yaml
  - allow-gateway-ingress.yaml
patches:
  - target:
      kind: NetworkPolicy
      name: flux-web-allow-gateway
    patch: |
      - op: replace
        path: /spec/podSelector
        value: {}
