apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  endpoints:
    - port: metrics
      path: /metrics
