apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      extraArgs:
        default-ssl-certificate: ingress-nginx/civilsnut-se-wildcard-tls
      nodeSelector:
        virt: "yes"
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

eyJhbGciOiJFUzI1NiIsImtpZCI6InpqbnRreGh2dXJsdTNnenFsZ3JjNHkzaG5hIiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiVVZQMkdCV0U3NUdRREZVR0QzTVlVUzJZWUUiLCIxcGFzc3dvcmQuY29tL3Rva2VuIjoieVRKVzdvWXJaeUh4Z3NuZWw1T2Y5Q0hsUi1tTGY2cVQiLCIxcGFzc3dvcmQuY29tL2Z0cyI6WyJ2YXVsdGFjY2VzcyJdLCIxcGFzc3dvcmQuY29tL3Z0cyI6W3sidSI6Im54bDU0N3RkZnFta3diZ3B1Mm12aXp2dGdlIiwiYSI6NDh9XSwiYXVkIjpbImNvbS4xcGFzc3dvcmQuY29ubmVjdCJdLCJzdWIiOiJIQVk0QzZSUkRCR1hOTEtLSkVaUVpaQUVEQSIsImV4cCI6MTc3ODI4NDc5OSwiaWF0IjoxNzYyNjk2NTM5LCJpc3MiOiJjb20uMXBhc3N3b3JkLmI1IiwianRpIjoianR1cTJnYmFpNWduYzc1dHNmN3RlbnFvaWUifQ.N4SagdUlPZQ0oteZLPDwL-FCIXNENerDFzYHsvsLIWdWNTN9rvYDTW1jjbv9yhtu0VEVMAmSFvIndQF0JAMVLg
