apiVersion: v1
kind: ConfigMap
metadata:
  name: vlogs-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  vlogs-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        url: http://victoria-logs-server.monitoring.svc:9428
        access: proxy
