apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: monitoring
      interval: 1h
  values:
    server:
      retentionPeriod: "7"
      persistentVolume:
        enabled: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 20Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
      nodeSelector:
        has-disk: "yes"
      vmServiceScrape:
        enabled: true
    vector:
      enabled: true
