---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  hostnames:
    - zigbee2mqtt.civilsnut.se
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
  rules:
    - backendRefs:
        - name: zigbee2mqtt
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
