---
apiVersion: v1
kind: Namespace
metadata:
  name: zigbee2mqtt
  labels:
    name: zigbee2mqtt
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/component: mqtt
    gateway.networking.k8s.io/allowed: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
