apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: connect
      version: "2.0.5"
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: external-secrets
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    connect:
      serviceType: ClusterIP
      # Reference to existing secret containing 1password-credentials.json
      # Create with: kubectl create secret generic op-credentials -n external-secrets --from-file=1password-credentials.json
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json

    operator:
      create: true
      token:
        name: onepassword-connect-token
        key: token

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    nodeSelector:
      has-disk: "yes"

    tolerations: []

    affinity: {}

    podSecurityContext:
      fsGroup: 65534

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
