apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: home-assistant
      version: "0.3.30"
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: home-assistant
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Image settings
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: "2025.10.3"
      pullPolicy: IfNotPresent

    # Controller type - use StatefulSet to match existing setup
    controller:
      type: StatefulSet

    # Environment variables
    env:
      - name: TZ
        value: "UTC"

    # Host network configuration - required for discovery
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    # Node selector to ensure scheduling on worker nodes with disk
    nodeSelector:
      has-disk: "yes"

    # Security context - needs to run as root for device access
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0

    securityContext:
      runAsUser: 0
      runAsGroup: 0

    # Service configuration
    service:
      type: ClusterIP
      port: 8123

    # Resource configuration
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

    # Persistence configuration
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      storageClass: longhorn

    # Probes configuration
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 15
      timeoutSeconds: 10

    # Configuration setup - disabled to use Helm chart defaults
    configuration:
      enabled: false

    # Additional volumes for custom components
    additionalVolumes: []

    # Additional volume mounts
    additionalMounts: []

    # Ingress disabled - using HTTPRoute instead
    ingress:
      enabled: false
