apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  url: https://pajikos.github.io/home-assistant-helm-chart
