apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pv-claim
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi