apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app: mqtt
data:
  # Map external port 1883 to mosquitto service
  1883: "mosquitto/mosquitto:1883"