apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: zigbee2mqtt
      version: "2.6.3"
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: zigbee2mqtt
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
      port: 8080

    statefulset:
      storage:
        enabled: true
        size: 1Gi
        storageClassName: longhorn
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
      nodeSelector:
        has-disk: "yes"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]

    zigbee2mqtt:
      timezone: Europe/Stockholm
      homeassistant:
        enabled: true
        discovery_topic: "homeassistant"
        status_topic: "hass/status"
      permit_join: false
      mqtt:
        server: "mqtt://mosquitto.mosquitto.svc.cluster.local:1883"
        user: admin
        password: mystrongmqttpassword
      serial:
        port: "tcp://192.168.1.195:6638"
        adapter: zstack
      frontend:
        enabled: true
        port: 8080
        host: ""
      advanced:
        channel: 11
        log_level: info
        cache_state: true
        last_seen: "ISO_8601"
        transmit_power: 5

    ingress:
      enabled: false
