apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vcluster-staging-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    app.kubernetes.io/name: vcluster-staging-cluster
    app.kubernetes.io/component: cluster-secret
    app.kubernetes.io/managed-by: external-secrets
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vcluster-staging-cluster
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          app.kubernetes.io/name: vcluster-staging
          app.kubernetes.io/component: argocd-cluster-secret
          app.kubernetes.io/managed-by: argocd
          environment: staging
      data:
        name: vcluster-staging
        server: https://staging.civilsnut.se:443
        config: |
          {
            "bearerToken": "{{ .bearerToken }}",
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .caData }}"
            }
          }
  refreshInterval: 1h
  data:
    - secretKey: bearerToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "vCluster Staging Credentials"
        property: bearerToken
    - secretKey: caData
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "vCluster Staging Credentials"
        property: caData
