apiVersion: v1
kind: Secret
metadata:
  name: vcluster-staging
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    app.kubernetes.io/name: vcluster-staging-cluster
    app.kubernetes.io/component: cluster-secret
    environment: staging
    kargo.akuity.io/stage: staging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
data:
  name: dmNsdXN0ZXItc3RhZ2luZw== # base64 for "vcluster-staging"
  server: aHR0cHM6Ly8xOTIuMTY4LjQuMTM= # base64 for "https://192.168.4.13"
  config: "" # This will be populated by a sync job
  insecure: dHJ1ZQ== # base64 for "true" - skip TLS verification for staging
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vcluster-staging-cluster-config-sync
  namespace: argocd
  labels:
    app.kubernetes.io/name: vcluster-staging-cluster
    app.kubernetes.io/component: config-sync-job
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vcluster-staging-cluster
        app.kubernetes.io/component: config-sync-job
    spec:
      restartPolicy: OnFailure
      serviceAccountName: argocd-server
      containers:
        - name: sync-config
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Copying kubeconfig from external secret to ArgoCD cluster secret..."

              # Get the kubeconfig from the external secret
              KUBECONFIG_DATA=$(kubectl get secret vcluster-staging-kubeconfig-raw -n argocd -o jsonpath='{.data.kubeconfig}')

              if [ -z "$KUBECONFIG_DATA" ]; then
                echo "Error: Could not retrieve kubeconfig from external secret"
                exit 1
              fi

              # Update the ArgoCD cluster secret with the kubeconfig
              kubectl patch secret vcluster-staging -n argocd --type merge -p="{\"data\":{\"config\":\"$KUBECONFIG_DATA\"}}"

              echo "ArgoCD cluster secret updated successfully"

              # Verify the secret is properly formatted
              kubectl get secret vcluster-staging -n argocd -o yaml
