# vCluster 0.26.0 configuration with ClusterIP service (using gateway routing)
controlPlane:
  service:
    enabled: true
    spec:
      type: ClusterIP
  proxy:
    extraSANs:
      - staging.civilsnut.se
  scheduling:
    nodeSelector:
      has-disk: "yes"
