# vCluster 0.26.0 configuration with LoadBalancer service
controlPlane:
  service:
    enabled: true
    spec:
      type: LoadBalancer
  proxy:
    extraSANs:
      - staging.civilsnut.se
  statefulSet:
    scheduling:
      nodeSelector:
        has-disk: "yes"
