apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vcluster-staging-cluster-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: vcluster-staging-cluster
    app.kubernetes.io/component: cluster-secret
    app.kubernetes.io/managed-by: external-secrets
    environment: staging
    kargo.akuity.io/stage: staging
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: vcluster-staging-cluster
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          app.kubernetes.io/name: vcluster-staging-cluster
          app.kubernetes.io/component: cluster-secret
          app.kubernetes.io/managed-by: external-secrets
          environment: staging
          kargo.akuity.io/stage: staging
      data:
        name: "vcluster-staging"
        server: "{{ .kubeconfig | fromYaml | .clusters | first | .cluster.server }}"
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .kubeconfig | fromYaml | .clusters | first | .cluster.certificate-authority-data }}",
              "certData": "{{ .kubeconfig | fromYaml | .users | first | .user.client-certificate-data }}",
              "keyData": "{{ .kubeconfig | fromYaml | .users | first | .user.client-key-data }}"
            },
            "bearerToken": "",
            "awsAuthConfig": null,
            "execProviderConfig": null
          }
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: "vcluster-staging-kubeconfig"
        property: "kubeconfig"
