apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager-kubernetes-store
  namespace: staging
  labels:
    app.kubernetes.io/name: vcluster-staging
    app.kubernetes.io/component: cert-manager-secretstore
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
      auth:
        serviceAccount:
          name: "external-secrets"
      remoteNamespace: "cert-manager"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vcluster-wildcard-cert-sync
  namespace: staging
  labels:
    app.kubernetes.io/name: vcluster-staging
    app.kubernetes.io/component: wildcard-cert-external-secret
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: cert-manager-kubernetes-store
    kind: SecretStore
  target:
    name: civilsnut-se-wildcard-tls
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: civilsnut-se-wildcard-tls
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: civilsnut-se-wildcard-tls
        property: tls.key
